"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.countUnreadNotifications = exports.getUnreadNotificationIds = exports.markAllNotificationsReadInList = exports.markNotificationReadInList = void 0;
const markNotificationReadInList = (notifications, notificationId) => notifications.map((item) => (item.id === notificationId ? { ...item, read: true } : item));
exports.markNotificationReadInList = markNotificationReadInList;
const markAllNotificationsReadInList = (notifications) => notifications.map((item) => ({ ...item, read: true }));
exports.markAllNotificationsReadInList = markAllNotificationsReadInList;
const getUnreadNotificationIds = (notifications) => notifications.filter((item) => !item.read).map((item) => item.id);
exports.getUnreadNotificationIds = getUnreadNotificationIds;
const countUnreadNotifications = (notifications) => notifications.filter((item) => !item.read).length;
exports.countUnreadNotifications = countUnreadNotifications;
