"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = __importDefault(require("assert"));
const languageUtils_1 = require("../src/shared/utils/languageUtils");
assert_1.default.strictEqual(languageUtils_1.languageDefinitions.length, 2);
assert_1.default.strictEqual(languageUtils_1.languageDefinitions[0].code, 'en');
assert_1.default.strictEqual(languageUtils_1.languageDefinitions[1].code, 'de');
assert_1.default.strictEqual((0, languageUtils_1.getLanguageStorageKey)(undefined), null);
assert_1.default.strictEqual((0, languageUtils_1.getLanguageStorageKey)(null), null);
assert_1.default.strictEqual((0, languageUtils_1.getLanguageStorageKey)('user-1'), 'employee-portal-language:user-1');
assert_1.default.strictEqual((0, languageUtils_1.isValidLanguage)('en'), true);
assert_1.default.strictEqual((0, languageUtils_1.isValidLanguage)('de'), true);
assert_1.default.strictEqual((0, languageUtils_1.isValidLanguage)('fr'), false);
assert_1.default.strictEqual((0, languageUtils_1.isValidLanguage)(null), false);
assert_1.default.strictEqual((0, languageUtils_1.resolveStoredLanguage)('de'), 'de');
assert_1.default.strictEqual((0, languageUtils_1.resolveStoredLanguage)('fr'), 'en');
assert_1.default.strictEqual((0, languageUtils_1.resolveStoredLanguage)(null), 'en');
assert_1.default.strictEqual((0, languageUtils_1.interpolate)('Hello world'), 'Hello world');
assert_1.default.strictEqual((0, languageUtils_1.interpolate)('Hello {name}', { name: 'Adeel' }), 'Hello Adeel');
assert_1.default.strictEqual((0, languageUtils_1.interpolate)('{count} shifts', { count: 5 }), '5 shifts');
assert_1.default.strictEqual((0, languageUtils_1.interpolate)('Hi {name}, {name} again', { name: 'Sam' }), 'Hi Sam, {name} again');
console.log('tests/languageUtils.test.ts OK');
