"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = __importDefault(require("assert"));
const shiftConfirmationStatus_1 = require("../src/lib/shiftConfirmationStatus");
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.normalizeShiftConfirmationStatus)(undefined), 'not published');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.normalizeShiftConfirmationStatus)(''), 'not published');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.normalizeShiftConfirmationStatus)('pending'), 'pending');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.normalizeShiftConfirmationStatus)('Scheduled'), 'scheduled');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.normalizeShiftConfirmationStatus)('confirmed_by_employee'), 'confirmed by employee');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.normalizeShiftConfirmationStatus)('confirmed-by-employee'), 'confirmed by employee');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.normalizeShiftConfirmationStatus)('  confirmed by employee  '), 'confirmed by employee');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.normalizeShiftConfirmationStatus)('unknown status'), 'not published');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.getShiftConfirmationStatusLabel)('not published'), 'Not published');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.getShiftConfirmationStatusLabel)('pending'), 'Pending');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.getShiftConfirmationStatusLabel)('scheduled'), 'Scheduled');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.getShiftConfirmationStatusLabel)('assigned'), 'Assigned');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.getShiftConfirmationStatusLabel)('published'), 'Published');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.getShiftConfirmationStatusLabel)('confirmed'), 'Confirmed');
assert_1.default.strictEqual((0, shiftConfirmationStatus_1.getShiftConfirmationStatusLabel)('confirmed by employee'), 'Confirmed by employee');
console.log('tests/shiftConfirmationStatus.test.ts OK');
