"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = __importDefault(require("assert"));
const shiftPhase_1 = require("../src/shared/utils/shiftPhase");
const start = '2026-03-10T08:00:00Z';
const end = '2026-03-10T16:00:00Z';
assert_1.default.strictEqual((0, shiftPhase_1.getShiftPhase)(start, end, new Date('2026-03-10T07:59:59Z')), 'upcoming', 'before shift start should be upcoming');
assert_1.default.strictEqual((0, shiftPhase_1.getShiftPhase)(start, end, new Date('2026-03-10T08:00:00Z')), 'live', 'exact shift start should be live');
assert_1.default.strictEqual((0, shiftPhase_1.getShiftPhase)(start, end, new Date('2026-03-10T12:00:00Z')), 'live', 'between start and end should be live');
assert_1.default.strictEqual((0, shiftPhase_1.getShiftPhase)(start, end, new Date('2026-03-10T16:00:00Z')), 'live', 'exact shift end is still live with current logic');
assert_1.default.strictEqual((0, shiftPhase_1.getShiftPhase)(start, end, new Date('2026-03-10T16:00:01Z')), 'past', 'after shift end should be past');
assert_1.default.strictEqual(shiftPhase_1.phaseMeta.past.label, 'Past shift');
assert_1.default.strictEqual(shiftPhase_1.phaseMeta.live.label, 'Live now');
assert_1.default.strictEqual(shiftPhase_1.phaseMeta.upcoming.label, 'Upcoming');
assert_1.default.ok(shiftPhase_1.phaseMeta.past.icon.length > 0);
assert_1.default.ok(shiftPhase_1.phaseMeta.live.icon.length > 0);
assert_1.default.ok(shiftPhase_1.phaseMeta.upcoming.icon.length > 0);
assert_1.default.ok(shiftPhase_1.phaseMeta.past.color.startsWith('#'));
assert_1.default.ok(shiftPhase_1.phaseMeta.live.background.startsWith('#'));
assert_1.default.ok(shiftPhase_1.phaseMeta.upcoming.background.startsWith('#'));
console.log('tests/shiftPhase.test.ts OK');
